[build]
  base = "frontend/client"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://your-backend-url.com"  # Update this with your actual backend URL

[dev]
  command = "npm start"
  targetPort = 3000
  publish = "build"
