[build]
  command = "cd frontend/client && npm install && npm run build"
  publish = "frontend/client/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9" 