[build]
  base = "frontend/client"
  publish = "build"
  command = "npm ci && npm run build"

[build.environment]
  REACT_APP_API_URL = "https://your-backend-url.com"  # Update this with your actual backend URL
  NODE_ENV = "production"

[dev]
  command = "npm start"
  targetPort = 3000
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm ci && npm run build"
  environment = {
    NODE_ENV = "production"
  }

[context.deploy-preview]
  command = "npm ci && npm run build"
  environment = {
    NODE_ENV = "production"
  }

[context.branch-deploy]
  command = "npm ci && npm run build"
  environment = {
    NODE_ENV = "production"
  }

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"

[context.branch-deploy.environment]
  NODE_ENV = "production"
